<?php

namespace Container9hCJHZR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKeyGenerateCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\KeyGenerateCommand' shared autowired service.
     *
     * @return \App\Command\KeyGenerateCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/KeyGenerateCommand.php';

        $container->privates['App\\Command\\KeyGenerateCommand'] = $instance = new \App\Command\KeyGenerateCommand((\dirname(__DIR__, 4).'/.env'));

        $instance->setName('key-generate');
        $instance->setDescription('Generate APP_SECRET');

        return $instance;
    }
}
